# Generated by Django 4.0.3 on 2022-04-10 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=200)),
                ('bottun', models.CharField(max_length=50)),
                ('showMenu', models.BooleanField(default=False)),
                ('borrowed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='booksec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Borower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowedBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateFrom', models.DateTimeField(verbose_name='date published')),
                ('DateTo', models.DateTimeField(verbose_name='date published')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liprary.book')),
                ('borowerinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liprary.borower')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liprary.booksec'),
        ),
    ]
