# Generated by Django 4.0.3 on 2022-04-10 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liprary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorowerInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateFrom', models.DateTimeField(verbose_name='date published')),
                ('DateTo', models.DateTimeField(verbose_name='date published')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liprary.book')),
            ],
        ),
        migrations.RemoveField(
            model_name='borrowedbooks',
            name='book',
        ),
        migrations.RemoveField(
            model_name='borrowedbooks',
            name='borowerinfo',
        ),
        migrations.DeleteModel(
            name='Borower',
        ),
        migrations.DeleteModel(
            name='BorrowedBooks',
        ),
    ]
